site_name: PortPy
site_description: Open-source Python library for radiation therapy planning and optimization.
site_author: PortPy Contributors
repo_url: https://github.com/PortPy-Project/PortPy
repo_name: PortPy on GitHub
theme:
  name: material
  logo: images/PortPy_logo.png
  favicon: images/PortPy_logo.png
  palette:
    - scheme: default
      primary: deep purple    # Modern, professional tone
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    #- navigation.tabs If enabled, tabs will be shown for each page on the top of the page.
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.annotate
nav:
  - Home: index.md
  - Installation: installation.md
#  - Getting Started: getting-started.md
  - User Guide:
      - Overview: user-guide/overview.md
      - Workflow: user-guide/workflow.md
      - Command-Line Interface: user-guide/cli.md
  - Tutorials:
      - Loading Data: tutorials/loading-data.md
      - Optimization Example: tutorials/optimization.md
      - Beam Orientation: tutorials/beam-orientation.md
      - Custom Algorithms: tutorials/custom-algorithms.md
  - Examples: examples.md
  - API Reference:
      - PortPy API: api/portpy.md
#  - Datasets: datasets.md
  - Publications: publications.md
#  - About: about.md
  - Contributing: contributing.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [portpy]
  - tags
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PortPy-Project/PortPy
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/portpy-photon/
extra_javascript:
  - js/extra.js
extra_css:
  - styles/extra.css 
